%
(Generated by SketchUcam {1.2a})
(File: Plate_printouts.skp)
(Bit diameter: 1/8")
(Feed rate: 100"/min)
(Material Thickness: 1/4")
(Material length: 15" X width: 25")
(Overhead Gantry: true)
(Retract feed rate NOT limited to plunge feed rate)
(Optimization is ON)
(Z ZERO IS TABLETOP)
(www.PhlatBoyz.com)
(Loaded profile default)
G90 G20 G49 
M3 S15000
G0   Z0.3750    
G0 X0 Y0 (home)
M05
M30
%
